### ISSUE TITLE
为什么只能添加一个常量

### ISSUE THREAD

**Issue by lehhair** [idanran/myrtus#10]
为什么只能添加一个常量，是我操作不对吗

**Comment by idanran** [comment]
> 为什么只能添加一个常量，是我操作不对吗

请提供版本信息

**Comment by idanran** [comment]
还有配置页面的截图

**Comment by lehhair** [comment]
> 还有配置页面的截图

![image](https://github.com/idanran/myrtus/assets/82690391/d4ea3fef-c666-4207-8310-ea2219282c2b)
像这样添加了两个然后点保存配置后就只剩一个了

**Comment by lehhair** [comment]
> > > 还有配置页面的截图
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/82690391/251418855-d4ea3fef-c666-4207-8310-ea2219282c2b.png)
> > 像这样添加了两个然后点保存配置后就只剩一个了
> 
> 请将所有插件更新至最新版本（包括 koishi）

我去试试

**Comment by lehhair** [comment]
> > > 还有配置页面的截图
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/82690391/251418855-d4ea3fef-c666-4207-8310-ea2219282c2b.png)
> > 像这样添加了两个然后点保存配置后就只剩一个了
> 
> 请将所有插件更新至最新版本（包括 koishi）

更新后koishi就崩了...

**Comment by idanran** [comment]
> > > > 还有配置页面的截图
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/82690391/251418855-d4ea3fef-c666-4207-8310-ea2219282c2b.png)
> > > 像这样添加了两个然后点保存配置后就只剩一个了
> > 
> > 
> > 请将所有插件更新至最新版本（包括 koishi）
> 
> 更新后koishi就崩了...

可以截图吗

**Comment by lehhair** [comment]
> > > > > 还有配置页面的截图
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/82690391/251418855-d4ea3fef-c666-4207-8310-ea2219282c2b.png)
> > > > 像这样添加了两个然后点保存配置后就只剩一个了
> > > 
> > > 
> > > 请将所有插件更新至最新版本（包括 koishi）
> > 
> > 
> > 更新后koishi就崩了...
> 
> 可以截图吗

我重新安装了一下koishi，好了，但是这个互联插件依旧只能保存一个常量，我在想是不是我的操作不对，我来录个gif

**Comment by lehhair** [comment]
![msedge_2ECxSh4dFi](https://github.com/idanran/myrtus/assets/82690391/8e80e419-e2b9-4ccb-ac13-3f013e795e10)
就像这样

**Comment by idanran** [comment]
> ![msedge_2ECxSh4dFi](https://github.com/idanran/myrtus/assets/82690391/8e80e419-e2b9-4ccb-ac13-3f013e795e10)
> 就像这样

话说，你加koishi用户群了吗？

**Comment by lehhair** [comment]
> > ![msedge_2ECxSh4dFi](https://user-images.githubusercontent.com/82690391/251430199-8e80e419-e2b9-4ccb-ac13-3f013e795e10.gif)
> > 就像这样
> 
> 话说，你加koishi用户群了吗？

加了

**Comment by idanran** [comment]
> > > ![msedge_2ECxSh4dFi](https://user-images.githubusercontent.com/82690391/251430199-8e80e419-e2b9-4ccb-ac13-3f013e795e10.gif)
> > > 就像这样
> > 
> > 话说，你加koishi用户群了吗？
> 
> 加了

你看下群
