### ISSUE TITLE
請求適配adapter-red

### ISSUE THREAD

**Issue by Rem0rs** [idanran/myrtus#14]
使用[adapter-red](https://github.com/idanran/koishi-plugin-adapter-red#readme) 後，轉發功能無法使用

**Comment by idanran** [comment]
能否描述得具体一些

**Comment by Rem0rs** [comment]
之前使用的@chronocat/adapter接入qq平台，用於qq群和kook消息互傳。‎‎‎chronocat目前不支持Koishi 4.15.0所以改用了adapter-red接入qq. 後發現轉發消息功能失效，確認配置文件沒有填錯，日誌沒有任何報錯。另一個轉發插件[forward](https://common.koishi.chat/zh-CN/plugins/forward.html)可正常使用

**Comment by Rem0rs** [comment]
修改之後仍無法使用

**Comment by idanran** [comment]
把现有配置清除，然后重新配置试试

**Comment by idanran** [comment]
过几天我看看

**Comment by qys8888** [comment]
red的qq会报错：[2023-10-12 14:34:14.423] [ERROR] [Main] undefined
(node:81) UnhandledPromiseRejectionWarning: undefined
(node:81) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 37)
 

导致QQ不能发送消息

**Comment by qys8888** [comment]
一样的问题，请求适配

**Comment by eric2788** [comment]
我也一样

**Comment by idanran** [comment]
已适配，请更新适配器和本插件到最新版本。

**Comment by eric2788** [comment]
@idanran 我尝试使用 red <-> discord 互传，发现 red 转发 discord 时没有转发图片，但 discord 转发 red 就有

**Comment by idanran** [comment]
> @idanran 我尝试使用 red <-> discord 互传，发现 red 转发 discord 时没有转发图片，但 discord 转发 red 就有

请提供日志

**Comment by eric2788** [comment]
> > @idanran 我尝试使用 red <-> discord 互传，发现 red 转发 discord 时没有转发图片，但 discord 转发 red 就有
> 
> 我这里是可以发图的，建议把所有依赖更新到最新版本再进行尝试。

應該是這個？ ![SmartSelect_20231017_085237_Chrome.jpg](https://github.com/idanran/myrtus/assets/6276840/b7991d74-861a-4d30-b320-8b36e78d7904)

我剛剛把red適配器更新最新版後還是不行

**Comment by idanran** [comment]
> > > @idanran 我尝试使用 red <-> discord 互传，发现 red 转发 discord 时没有转发图片，但 discord 转发 red 就有
> > 
> > 我这里是可以发图的，建议把所有依赖更新到最新版本再进行尝试。
> 
> 我只看到這個錯誤
> ![SmartSelect_20231017_085237_Chrome.jpg](https://github.com/idanran/myrtus/assets/6276840/b7991d74-861a-4d30-b320-8b36e78d7904)
> 
> 我剛剛把red適配器更新最新版後還是不行

能把发的消息截图一下吗

**Comment by eric2788** [comment]
![SmartSelect_20231017_090906_QQ.jpg](https://github.com/idanran/myrtus/assets/6276840/f416c7f5-4ade-4017-be58-97270421e276)

**Comment by idanran** [comment]
> ![SmartSelect_20231017_090906_QQ.jpg](https://github.com/idanran/myrtus/assets/6276840/f416c7f5-4ade-4017-be58-97270421e276)
> 
> 

把 red 和 discord 适配器更新一下

**Comment by eric2788** [comment]
ok 我重启之后就有了，谢谢！

**Comment by idanran** [comment]
> ok 我重启之后就有了，谢谢！

不客气

**Comment by eric2788** [comment]
> > ok 我重启之后就有了，谢谢！
> 
> 不客气

问个问题，有打算解析QQ转发消息吗，例如在discord换成thread，在telegram换成comment之类

**Comment by idanran** [comment]
> 问个问题，有打算解析QQ转发消息吗，例如在discord换成thread，在telegram换成comment之类

暂时没有打算，因为时间不充裕。

**Comment by idanran** [comment]
你可以提个 issue，等有时间我看看能不能做。
