### ISSUE TITLE
QQ频道下昵称解析异常

### ISSUE THREAD

**Issue by XingNian-www** [idanran/myrtus#16]
QQ频道到QQ的转发中，@时ID没有被转换为昵称
QQ至TG转发中，@时ID没有被转换为昵称

**Comment by XingNian-www** [comment]
![Uploading Screenshot_2023-10-24-22-48-56-024_org.telegram.messenger-edit.jpg…]()

**Comment by XingNian-www** [comment]
![Screenshot_2023-10-24-22-48-56-024_org telegram messenger-edit](https://github.com/idanran/myrtus/assets/44593434/d65a1503-b0a7-4959-a1b2-15e04f67232c)
![Screenshot_2023-10-24-22-48-12-089_com tencent mobileqq-edit](https://github.com/idanran/myrtus/assets/44593434/7ba10093-77db-420c-b53b-eddcf5cdc50a)

**Comment by idanran** [comment]
请提供使用的适配器以及其版本号

**Comment by XingNian-www** [comment]
Binaries:
Node: 16.19.1
Yarn: 3.5.0
Koishi:
Core: 4.15.2
Console: 5.16.1
Koishi Desktop: 0.10.7

myrtus/forward:3.6.2
koishi-plugin-adapter-onebot:6.1.2
@koishijs/plugin-adapter-telegram:4.1.4

**Comment by idanran** [comment]
这个是因为 adapter-onebot 拿不到 at 对象的 name，暂时无法解决
