### ISSUE TITLE
功能请求：支持监听所有的频道，支持过滤selfId

### ISSUE THREAD

**Issue by 9cats** [idanran/myrtus#18]
我想让两个不同的邮箱的邮件转发到 telegram 上，但是在 adapter-mail 上，不同发送者的 `channelId` 和 `guildId` 都不一样，在配置时被困惑。
希望在配置项中的 `channelId` 和 `guildId` 能用 `*` 来表示监听全部，另外希望添加`selfId`的过滤支持，更好区分不同的实例。

**Comment by 9cats** [comment]
应该可以这样实现，不过还没有尝试过。
https://github.com/9cats/myrtus/commit/9118a20de8ee9a8a784460acf30aa089005bba0c

**Comment by idanran** [comment]
「另外希望添加selfId的过滤支持」
能具体描述一下吗

**Comment by idanran** [comment]
已在 3.7.0 实装
