### ISSUE TITLE
尝试把邮件转发到qq机器人但没有成功

### ISSUE THREAD

**Issue by ZGLinus** [idanran/myrtus#19]
adapter信息
![图片](https://github.com/idanran/myrtus/assets/69845097/3ae2410b-e06f-4b32-a434-7fdcdfd7e6b0)
常量配置
![图片](https://github.com/idanran/myrtus/assets/69845097/aea317c1-87bd-443d-b315-78ae28e01dd6)
![图片](https://github.com/idanran/myrtus/assets/69845097/3b5e5ba3-300c-4659-abbd-90eb68378d95)
转发规则配置
![图片](https://github.com/idanran/myrtus/assets/69845097/6bf59290-01d3-4e53-8ab6-c2f5e46fdcf6)
系统信息
```
System:
    OS: Linux 4.19 Alpine Linux
    CPU: (4) arm64 Cortex-A55
Binaries:
    Node: 18.17.1
    Yarn: 3.6.2
Koishi:
    Core: 4.15.4
    Console: 5.18.1
```
adapter 都可以正常使用，常量配置里面的信息也和 inspect 命令保持一致，我哪里做错了？

**Comment by idanran** [comment]
首先检查 mail 的自身 ID 是否正确，其次可以尝试把 mail 的频道 ID 和群组 ID 改成`*`。

**Comment by ZGLinus** [comment]
还是没有办法实现转发

**Comment by ZGLinus** [comment]
![图片](https://github.com/idanran/myrtus/assets/69845097/5b272073-c5d1-492c-8e09-b87c9b580cfd)

**Comment by idanran** [comment]
myrtus/forward 的版本是多少

**Comment by ZGLinus** [comment]
3.7.0

**Comment by idanran** [comment]
把 mail 的自身 ID 改成`*`试试

**Comment by ZGLinus** [comment]
也不行啊，有没有调出debug日志的方法？

**Comment by idanran** [comment]
> 也不行啊，有没有调出debug日志的方法？

在 koishi.yml 的底部加上：
```yaml
logger: 
   levels: 
     forward: 3
```

**Comment by ZGLinus** [comment]
经过测试，不知道为什么，koishi 接收到的信息没有被 forward 捕捉到，甚至我把 test 的平台从 mail 换到 red 也不行。

**Comment by idanran** [comment]
更新到 3.7.1 试试

**Comment by ZGLinus** [comment]
正常了
