### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by XingNian-www** [idanran/myrtus#5]
1.Telegram适配器支持话题后转发选项可能需要更新一下
现在是只看数据库中的ID,但是TG不同群组的话题ID可能重复
2.转发添加反向转发选项,减少配置冗余
我现在4个群组的转发就已经要写4*4次配置,简直离谱(
3.回复使用re太乱了,如果能支持原生回复就好了

**Comment by idanran** [comment]
原生回复在做了。

**Comment by idanran** [comment]
@XingNian-www  已完成，参见 #6。
