### ISSUE TITLE
平台名选择onebot时不能保存

### ISSUE THREAD

**Issue by cuncun-edg** [idanran/myrtus#9]
![image](https://github.com/idanran/myrtus/assets/77426305/14d97202-957c-44fc-88cf-bfca783778f6)

**Comment by idanran** [comment]
> ![image](https://user-images.githubusercontent.com/77426305/248300895-14d97202-957c-44fc-88cf-bfca783778f6.png)

请提供版本信息

**Comment by cuncun-edg** [comment]
> 请提供版本信息

System:
    OS: Linux 3.10 Alpine Linux
    CPU: (4) x64 AMD Ryzen 5 4600H with Radeon Graphics

Binaries:
    Node: 18.16.0
    Yarn: 1.22.19

Koishi:
    Core: 4.13.4
    Console: 5.11.4

并且无法保存两个及以上的constants内容。

**Comment by idanran** [comment]
> > 请提供版本信息
> 
> System:
>     OS: Linux 3.10 Alpine Linux
>     CPU: (4) x64 AMD Ryzen 5 4600H with Radeon Graphics
> 
> Binaries:
>     Node: 18.16.0
>     Yarn: 1.22.19
> 
> Koishi:
>     Core: 4.13.4
>     Console: 5.11.4
> 
> 并且无法保存两个及以上的constants内容。

有点诡异啊

**Comment by cuncun-edg** [comment]
我搞了一晚上，是用虚拟机用docker搭建的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月23日(星期五) 晚上11:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [idanran/myrtus] 平台名选择onebot时不能保存 (Issue #9)





   
请提供版本信息
  
System:
 OS: Linux 3.10 Alpine Linux
 CPU: (4) x64 AMD Ryzen 5 4600H with Radeon Graphics
 
Binaries:
 Node: 18.16.0
 Yarn: 1.22.19
 
Koishi:
 Core: 4.13.4
 Console: 5.11.4
 
并且无法保存两个及以上的constants内容。
  
有点诡异啊

**Comment by idanran** [comment]
嗯呐

**Comment by idanran** [comment]
这个 bug 可能触及到上游的问题，因此需要一些时间。

**Comment by cuncun-edg** [comment]
> 这个 bug 可能触及到上游的问题，因此需要一些时间。

经测试降低koishi版本可用，但还是不能直接保存onebot，需要切换一下，其他平台名，再选择onebot

**Comment by idanran** [comment]
> > 这个 bug 可能触及到上游的问题，因此需要一些时间。
> 
> 经测试降低koishi版本可用，但还是不能直接保存onebot，需要切换一下，其他平台名，再选择onebot

嗷

**Comment by idanran** [comment]
> > 这个 bug 可能触及到上游的问题，因此需要一些时间。
> 
> 经测试降低koishi版本可用，但还是不能直接保存onebot，需要切换一下，其他平台名，再选择onebot

已解决，请将 koishi (包括 console) 和 @myrtus/forward 更新至最新版本。
